import os
import subprocess
import tempfile
from pathlib import Path

from fontTools.misc.transform import Scale
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.svgLib import SVGPath
from fontTools.ttLib import TTFont

from emoji_font_generator.input.config import get_conlang_font_filename, get_dictionary
from emoji_font_generator.project import get_project_dir


def add_svg_ligatures_to_font(
        input_font_path: str | Path,
        ligature_dict: dict[str, str],
        output_font_path: str | Path,
        new_font_name: str = 'generated by emoji-font-generator',
) -> None:
    font = TTFont(input_font_path)
    try:
        font.setFontRevision(new_font_name)
    except Exception:
        print('Could not set new name to font')

    # Get font metrics
    upm = font['head'].unitsPerEm
    ascender = font['hhea'].ascent
    descender = font['hhea'].descent

    # Get existing glyph tables
    glyf = font['glyf']
    hmtx = font['hmtx']

    # Track new glyphs and their components for ligature rules
    new_glyphs = []
    ligature_rules = []

    for ligature_name, svg_path in ligature_dict.items():
        if not Path(svg_path).exists():
            print(f"SVG file {svg_path} does not exist")
            continue

        print(f"Processing {ligature_name}...")

        # Parse ligature components (e.g., "f_i" -> ["f", "i"])
        components = ligature_name.split('_') if '_' in ligature_name else list(ligature_name)

        # Convert SVG to glyph outline
        glyph, advance_width = svg_to_glyph_with_picosvg(
            font,
            svg_path,
            upm,
            ascender,
            descender,
            # is_ttf=True  # Set to False for CFF fonts
        )

        # Add glyph to font
        add_glyph_to_font(font, ligature_name, glyph, advance_width)
        new_glyphs.append(ligature_name)

        # Store ligature rule
        ligature_rules.append((components, ligature_name))

    # Add ligature substitutions to GSUB table
    add_ligature_substitutions(font, ligature_rules)

    # Save the font
    font.save(output_font_path)
    print(f"Font saved to {output_font_path}")


def svg_to_glyph_with_picosvg(font: TTFont, svg_path: str | Path, upm, ascender, descender):
    """
    Convert SVG to glyph using picosvg for better path handling
    """
    from picosvg.svg import SVG as picoSVG
    from fontTools.pens.t2CharStringPen import T2CharStringPen
    from fontTools.pens.transformPen import TransformPen

    # Read and normalize SVG
    with open(svg_path, 'r', encoding='utf-8-sig') as f:
        svg_content = f.read()

    # Convert to picosvg format (normalizes paths, removes transforms)
    picosvg = picoSVG.fromstring(svg_content).topicosvg()

    # Get viewBox
    x, y, width, height = picosvg.view_box()

    # Calculate scale
    font_height = ascender - descender
    scale = font_height / height

    # Create pen for CFF outlines (cubic curves)
    # pen = T2CharStringPen(upm, None)
    pen = TTGlyphPen(font.getGlyphSet())
    transform = Scale(scale, -scale).translate(-x, -height)
    transform_pen = TransformPen(pen, transform)

    # Draw
    svg_pen = SVGPath(None)
    svg_pen.root = picosvg.svg_root
    svg_pen.draw(transform_pen)

    # glyph = pen.getCharString()
    glyph = pen.glyph()
    advance_width = int(width * scale)

    return glyph, advance_width


def add_glyph_to_font(font: TTFont, glyph_name, glyph, advance_width):
    """
    Add a new glyph to the font [citation:7]
    """
    # Update glyph order
    glyph_order = list(font.getGlyphOrder())
    if glyph_name not in glyph_order:
        glyph_order.append(glyph_name)
        font.setGlyphOrder(glyph_order)

    # Add to glyf table
    font['glyf'][glyph_name] = glyph

    # Get left side bearing (minimum X coordinate)
    if hasattr(glyph, 'xMin'):
        lsb = glyph.xMin
    else:
        lsb = 0

    # Add to horizontal metrics
    font['hmtx'][glyph_name] = (advance_width, lsb)


def add_ligature_substitutions(font: TTFont, ligature_rules):
    """
    Add OpenType ligature substitutions to GSUB table - CORRECTED VERSION
    """
    # Ensure GSUB table exists - this creates a proper table_G_S_U_B_ instance
    if 'GSUB' not in font:
        from fontTools.ttLib.tables import G_S_U_B_
        font['GSUB'] = G_S_U_B_.table_G_S_U_B_()

    # Get the GSUB table
    gsub = font['GSUB']
    if 'GSUB' in font:
        print(dir(font['GSUB']))  # Shows available methods/attributes
    # print(dir(gsub))  # Shows available methods/attributes
    # IMPORTANT: The table_G_S_U_B_ object itself is the table
    # You don't access a .table attribute - the object IS the table

    # The correct way to add features is using feaLib.builder
    # Don't try to manually manipulate GSUB tables

    # Create feature file content
    feature_content = """languagesystem DFLT dflt;
languagesystem latn dflt;

feature liga {
"""

    for components, ligature_name in ligature_rules:
        comp_str = ' '.join(components)
        feature_content += f"    sub {comp_str} by {ligature_name};\n"

    feature_content += "} liga;\n"

    # Write temporary feature file
    import tempfile
    import os
    with tempfile.NamedTemporaryFile(mode='w', suffix='.fea', delete=False) as f:
        f.write(feature_content)
        feature_file = f.name

    # Use addOpenTypeFeatures to properly build the GSUB table
    from fontTools.feaLib.builder import addOpenTypeFeatures
    try:
        addOpenTypeFeatures(font, feature_file)
        print("Ligature features added successfully")
    except Exception as e:
        print(f"Error adding features: {e}")
        print("Feature content:")
        print(feature_content)
    finally:
        os.unlink(feature_file)


def sanitize_ligature(ligature: str) -> str:
    ligature = ligature.lower()
    ligature = ligature.replace('á', 'a')
    ligature = ligature.replace('í', 'i')
    ligature = ligature.replace('ú', 'u')
    ligature = ligature.replace('é', 'e')
    ligature = ligature.replace('ó', 'o')
    ligature = ligature.replace(' ', '')
    ligature = ligature.replace('?', '')
    ligature = ligature.replace('(', '')
    ligature = ligature.replace(')', '')
    ligature = ligature.replace('\n', '')
    ligature = ligature.replace(',', '')
    ligature = ligature.replace('.', '')
    ligature = ligature.replace('-', '')
    ligature = ligature.replace('\'', '')
    return ligature


def get_ligatures_map() -> dict[str, str]:
    rootdir = get_project_dir()
    dct = get_dictionary()
    ligatures_map = {}
    for wf_info in dct:
        clean_word = wf_info['conlang']
        clean_word = sanitize_ligature(clean_word)
        ligatures_map[clean_word] = f'{rootdir}/emojis/combined/{wf_info["natural"]}.svg'
    return ligatures_map
